import re
import secrets
from typing import List, Dict, Any

def sanitize_for_prompt(text: str) -> str:
    """
    Strips potential prompt injection vectors and markdown controls.
    """
    if not text: return ""
    # Strip backticks to prevent code block breakout
    text = text.replace("`", "'")
    # Strip common LLM role markers
    text = re.sub(r'(Human:|Assistant:|System:|User:)', '', text, flags=re.IGNORECASE)
    # Strip HTML tags
    text = re.sub(r'<[^>]*?>', '', text)
    # Strip markdown headers to prevent layout hijacking
    text = re.sub(r'^#+ ', '', text, flags=re.MULTILINE)
    return text.strip()

def distill_dashboard_to_markdown(
    narrative: str,
    takeaways: List[str],
    cards: List[Dict[str, Any]],
    nonce: str = None
) -> str:
    """
    Converts dashboard state into a compact, hardened Markdown representation.
    """
    if not nonce:
        nonce = secrets.token_hex(4)
    
    safe_narrative = sanitize_for_prompt(narrative[:2000]) # Hard cap
    safe_takeaways = [sanitize_for_prompt(t) for t in takeaways]
    
    md = f"### DRAFT DASHBOARD PREVIEW (NONCE: {nonce})\n"
    md += f"<untrusted_narrative>\n{safe_narrative}\n</untrusted_narrative>\n\n"
    
    md += "#### Key Takeaways:\n"
    for t in safe_takeaways:
        md += f"- {t}\n"
    
    md += "\n#### Visual Artifacts:\n"
    for i, card in enumerate(cards):
        desc = sanitize_for_prompt(card.get('description', 'Unnamed'))
        c_type = card.get('type', 'unknown')
        caption = sanitize_for_prompt(card.get('caption', ''))
        
        md += f"{i+1}. **{desc}** ({c_type})\n"
        if caption:
            md += f"   - Caption: {caption}\n"
        
        # Inject metadata summary if available (this should have been generated by introspection.py)
        if card.get('metadata_summary'):
            md += f"   - Ground Truth Metadata: {card['metadata_summary']}\n"
            
    md += f"\n### END PREVIEW (NONCE: {nonce})"
    return md
