import re
import secrets
from typing import List, Dict, Any

def sanitize_for_prompt(text: str) -> str:
    """
    Strips potential prompt injection vectors and markdown controls.
    """
    if not text: return ""
    # Strip backticks to prevent code block breakout
    text = text.replace("`", "'")
    # Strip common LLM role markers
    text = re.sub(r'(Human:|Assistant:|System:|User:)', '', text, flags=re.IGNORECASE)
    # Strip HTML tags
    text = re.sub(r'<[^>]*?>', '', text)
    # Strip markdown headers to prevent layout hijacking
    text = re.sub(r'^#+ ', '', text, flags=re.MULTILINE)
    return text.strip()

def distill_dashboard_to_markdown(
    narrative: str,
    takeaways: List[str],
    cards: List[Dict[str, Any]],
    nonce: str = None,
    sections: List[Dict[str, Any]] = None,
) -> str:
    """
    Converts dashboard state into a compact, hardened Markdown representation.

    `sections` is the recipe-driven structure the dashboard actually renders. Including it
    is what lets the Critique judge the report as published — an empty or absent section is
    a real defect in the deliverable, and previewing only the narrative and the charts hid
    exactly that class of gap.
    """
    if not nonce:
        nonce = secrets.token_hex(4)
    
    safe_narrative = sanitize_for_prompt(narrative[:2000]) # Hard cap
    safe_takeaways = [sanitize_for_prompt(t) for t in takeaways]
    
    md = f"### DRAFT DASHBOARD PREVIEW (NONCE: {nonce})\n"
    md += f"<untrusted_narrative>\n{safe_narrative}\n</untrusted_narrative>\n\n"
    
    md += "#### Key Takeaways:\n"
    for t in safe_takeaways:
        md += f"- {t}\n"
    
    if sections:
        md += "\n#### Pipeline Sections (the dashboard body, one per recipe step):\n"
        for sec in sections:
            status = "not executed" if sec.get("status") == "not_executed" else sec.get("status", "")
            md += f"{sec.get('index')}. **{sanitize_for_prompt(str(sec.get('title', '')))}** ({status})\n"
            note = sanitize_for_prompt(str(sec.get("note") or ""))[:600]
            md += f"   - Commentary: {note if note else 'MISSING — this section has no write-up.'}\n"
            if sec.get("metrics"):
                md += ("   - Metrics: "
                       + ", ".join(f"{k}={v}" for k, v in sec["metrics"].items()) + "\n")
            if sec.get("cards"):
                md += f"   - Charts: {len(sec['cards'])}\n"

    md += "\n#### Visual Artifacts:\n"
    for i, card in enumerate(cards):
        desc = sanitize_for_prompt(card.get('description', 'Unnamed'))
        c_type = card.get('type', 'unknown')
        caption = sanitize_for_prompt(card.get('caption', ''))
        
        md += f"{i+1}. **{desc}** ({c_type})\n"
        if caption:
            md += f"   - Caption: {caption}\n"
        
        # Inject metadata summary if available (this should have been generated by introspection.py)
        if card.get('metadata_summary'):
            md += f"   - Ground Truth Metadata: {card['metadata_summary']}\n"
            
    md += f"\n### END PREVIEW (NONCE: {nonce})"
    return md
