import os
import yaml
import re
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field

def _extract_rationale(body_str: str, fallback: str = "") -> str:
    """Pull the ## Rationale section from a recipe body.

    Tolerant of recipes that end the section with EOF rather than a trailing `##`
    heading. Falls back to any frontmatter `rationale:` value (passed in) when the
    body has no parseable section, instead of clobbering it with an empty string.
    """
    match = re.search(r"##\s*Rationale\s*\n(.*?)(?:\n\s*##|\Z)", body_str, re.DOTALL)
    if match:
        extracted = match.group(1).strip()
        if extracted:
            return extracted
    return (fallback or "").strip()


class RecipeTask(BaseModel):
    id: str
    intent: str
    worker_tier: str
    depends_on: List[str] = []
    produces: List[str] = []
    # NOTE: `postconditions` are advisory contract-design aids that document a node's
    # success criteria for recipe authors. They are NOT evaluated at runtime — the
    # ExecutionHub builds the enforced contract from `produces`/`required_metrics`
    # only. Hard-asserting these arbitrary expressions would cause false failures on
    # forgetful local models, against the project's deliberate soft-fail philosophy.
    postconditions: List[str] = []
    required_metrics: List[str] = []
    # Skill IDs to inject (full body) into the Coder prompt for this node. When set,
    # the RecipeEnforcer uses these verbatim instead of keyword-scoring the intent.
    # Three-state on purpose: None (key absent) = fall back to discovery; [] (declared
    # empty) = no curated skill, suppress discovery; non-empty = use verbatim. The
    # empty/absent distinction is what lets a D3 recipe pin itself skill-free — see the
    # RecipeCompiler in server.py and approach_docs/014.
    attached_skills: Optional[List[str]] = None
    skippable_if: Optional[str] = None
    rationale_required: bool = False
    # Optional native-node safety net: the name (NATIVE_REGISTRY key) of a native that can
    # deterministically satisfy this node if the model exhausts all retries. Declares intent
    # only — the executor's local-fallback path (opt-in) is what actually invokes it. When
    # set, the node is model-generated by default (capability stays measured) with the native
    # available as a fallback, rather than the native being the always-on primary.
    fallback_native: Optional[str] = None
    # The exact Python call(s) that invoke `fallback_native` to satisfy this node, run in the
    # live kernel if the model exhausts retries. Must bind the node's `produces` variables
    # (upstream kernel state — df, X_test, etc. — is still live). e.g.
    # "km = gads_kaplan_meier(df, time_col=time_col, event_col=event_col); km_median = km['overall_median']".
    fallback_call: Optional[str] = None
    # Production mode (native-first) must NOT substitute the native for this node.
    #
    # Set it where the node's DELIVERABLE IS THE MODEL'S REASONING, not the computation —
    # the defended shortlist, the model card. Their natives exist as a floor so a weak model
    # cannot block a run, and a floor used as the ceiling defeats the node: `gads_default_
    # shortlist` ruled out deep learning "due to the tabular nature of the data", which is
    # true of every tabular dataset and therefore argues nothing, where the model named the
    # 41-level categorical that actually decided it (run e64f1c50 vs e1282fce, 2026-08-20).
    #
    # The native stays available as a post-exhaustion rescue in BOTH modes; this only forbids
    # pre-empting the model with it.
    model_required: bool = False
    # Optional authoring control over how this node appears in the final dashboard.
    # The dashboard skeleton is derived from the DAG itself (one section per node, in
    # DAG order) — this only tunes presentation. Keys:
    #   title (str)     — section heading; defaults to the prettified node id
    #   summary (str)   — one-line description shown under the heading; defaults to the intent
    #   collapsed (bool)— force the section into the collapsed "pipeline step" style even if
    #                     it produced evidence (auto-collapse applies to empty nodes anyway)
    report: Optional[Dict[str, Any]] = None

class Recipe(BaseModel):
    id: str
    version: str
    author: str
    applies_when: Dict[str, Any]
    requires: Dict[str, Any]
    dag: List[RecipeTask]
    invariants: List[str] = []
    rationale: str = ""

class Skill(BaseModel):
    id: str
    triggers: List[str]
    description: str = ""
    content: str = ""

class KnowledgeRegistry:
    TYPES = ("recipes", "skills", "native")

    def __init__(self, recipes_dir: str, overlay_root: str = "gads_data/knowledge"):
        # Shipped baseline (version-controlled IP, read-only in the studio).
        self.recipes_dir = recipes_dir
        shipped_root = os.path.dirname(recipes_dir)
        self.skills_dir = os.path.join(shipped_root, "skills")
        self.native_dir = os.path.join(shipped_root, "native")
        self._shipped = {"recipes": self.recipes_dir, "skills": self.skills_dir, "native": self.native_dir}
        # Writable user overlay: shadows shipped by id/filename. gads_data/ is git-ignored,
        # so user-authored/edited items never touch the shipped IP (approach_docs/017 §1).
        self.overlay_root = overlay_root
        self._overlay = {t: os.path.join(overlay_root, t) for t in self.TYPES}

        self.recipes: Dict[str, Recipe] = {}
        self.skills: Dict[str, Skill] = {}
        self._recipe_filepaths: Dict[str, str] = {}
        self._skill_filepaths: Dict[str, str] = {}
        # id -> "shipped" | "overlay" | "overridden", per type.
        self._provenance: Dict[str, Dict[str, str]] = {t: {} for t in self.TYPES}

        # Lazy semantic index (embedding-based skill retrieval). Import is local so a
        # missing fastembed never breaks the registry — semantic lookups just return [].
        from gads.core.skill_semantics import SkillEmbeddingIndex
        self.semantic_index = SkillEmbeddingIndex()
        self.load_recipes()
        self.load_skills()

    # ---- overlay-aware path helpers -------------------------------------- #
    def _dirs(self, item_type: str):
        """(shipped_dir, overlay_dir) for a knowledge type."""
        return self._shipped[item_type], self._overlay[item_type]

    def _resolve_path(self, item_type: str, filename: str) -> Optional[str]:
        """Path to a file by name, overlay shadowing shipped."""
        shp, ov = self._dirs(item_type)
        for base in (ov, shp):
            p = os.path.join(base, filename)
            if os.path.exists(p):
                return p
        return None

    def _list_files(self, item_type: str, ext: str = ".md") -> List[str]:
        shp, ov = self._dirs(item_type)
        names = set()
        for base in (shp, ov):
            if os.path.isdir(base):
                names.update(f for f in os.listdir(base) if f.endswith(ext))
        return sorted(names)

    def _write_overlay(self, item_type: str, filename: str, content: str) -> str:
        _, ov = self._dirs(item_type)
        os.makedirs(ov, exist_ok=True)
        path = os.path.join(ov, filename)
        with open(path, "w") as f:
            f.write(content)
        return path

    def provenance(self, item_type: str, item_id: Optional[str] = None):
        prov = self._provenance.get(item_type, {})
        return prov.get(item_id) if item_id is not None else dict(prov)

    def reset_to_shipped(self, item_type: str, filename: str):
        """Delete the overlay copy of a file, reverting to the shipped version."""
        _, ov = self._dirs(item_type)
        path = os.path.join(ov, filename)
        if not os.path.exists(path):
            raise ValueError("No overlay copy to reset (item is shipped or overlay-only).")
        os.remove(path)
        if item_type == "recipes":
            self.load_recipes()
        elif item_type == "skills":
            self.load_skills()

    def load_recipes(self):
        """Load shipped recipes, then overlay (overlay shadows a shipped id -> 'overridden')."""
        self.recipes = {}
        self._recipe_filepaths = {}
        self._provenance["recipes"] = {}
        shp, ov = self._dirs("recipes")
        for base, prov in ((shp, "shipped"), (ov, "overlay")):
            if not os.path.isdir(base):
                continue
            for filename in sorted(os.listdir(base)):
                if not filename.endswith(".md"):
                    continue
                path = os.path.join(base, filename)
                try:
                    with open(path, "r") as f:
                        content = f.read()
                    match = re.search(r"^---\s*\n(.*?)\n---\s*\n(.*)", content, re.DOTALL)
                    if not match:
                        continue
                    data = yaml.safe_load(match.group(1))
                    # Preserve a frontmatter `rationale:` rather than clobbering with an empty match.
                    data["rationale"] = _extract_rationale(match.group(2), data.get("rationale", ""))
                    recipe = Recipe(**data)
                    was_shipped = recipe.id in self.recipes
                    self.recipes[recipe.id] = recipe
                    self._recipe_filepaths[recipe.id] = path
                    self._provenance["recipes"][recipe.id] = "overridden" if (prov == "overlay" and was_shipped) else prov
                    print(f"  [Registry] Loaded recipe: {recipe.id} (v{recipe.version}) [{self._provenance['recipes'][recipe.id]}]")
                except Exception as e:
                    print(f"  [Registry] Error loading {filename}: {e}")

    def load_skills(self):
        """Load shipped skills, then overlay (overlay shadows a shipped id -> 'overridden')."""
        self.skills = {}
        self._skill_filepaths = {}
        self._provenance["skills"] = {}
        shp, ov = self._dirs("skills")
        for base, prov in ((shp, "shipped"), (ov, "overlay")):
            if not os.path.isdir(base):
                continue
            for filename in sorted(os.listdir(base)):
                if not filename.endswith(".md"):
                    continue
                path = os.path.join(base, filename)
                try:
                    with open(path, "r") as f:
                        content = f.read()
                    match = re.search(r"^---\s*\n(.*?)\n---\s*\n(.*)", content, re.DOTALL)
                    if not match:
                        continue
                    data = yaml.safe_load(match.group(1))
                    data["content"] = match.group(2).strip()
                    skill = Skill(**data)
                    was_shipped = skill.id in self.skills
                    self.skills[skill.id] = skill
                    self._skill_filepaths[skill.id] = path
                    self._provenance["skills"][skill.id] = "overridden" if (prov == "overlay" and was_shipped) else prov
                    print(f"  [Registry] Loaded skill: {skill.id} [{self._provenance['skills'][skill.id]}]")
                except Exception as e:
                    print(f"  [Registry] Error loading skill {filename}: {e}")
        # Keep the semantic index in sync with the skill collection (hot-edits included).
        self.semantic_index.rebuild(list(self.skills.values()))

    def list_items(self, item_type: Optional[str] = None) -> List[Dict[str, Any]]:
        """Unified library listing across types with metadata + provenance (studio)."""
        out: List[Dict[str, Any]] = []
        if item_type in (None, "recipe"):
            for rid, rec in self.recipes.items():
                aw = rec.applies_when or {}
                out.append({
                    "type": "recipe", "id": rid,
                    "filename": os.path.basename(self._recipe_filepaths.get(rid, "")),
                    "version": rec.version,
                    "task_type": aw.get("task_type") or [],
                    "data_modality": aw.get("data_modality") or [],
                    "capabilities": (rec.requires or {}).get("capabilities", []) or [],
                    "provenance": self._provenance["recipes"].get(rid),
                })
        if item_type in (None, "skill"):
            for sid, sk in self.skills.items():
                out.append({
                    "type": "skill", "id": sid,
                    "filename": os.path.basename(self._skill_filepaths.get(sid, "")),
                    "description": sk.description, "triggers": sk.triggers,
                    "provenance": self._provenance["skills"].get(sid),
                })
        if item_type in (None, "native"):
            shp, ov = self._dirs("native")
            for fn in self.list_native_files():
                in_ov = os.path.exists(os.path.join(ov, fn))
                in_shp = os.path.exists(os.path.join(shp, fn))
                prov = "overridden" if (in_ov and in_shp) else ("overlay" if in_ov else "shipped")
                out.append({"type": "native", "id": fn, "filename": fn, "provenance": prov})
        return sorted(out, key=lambda i: (i["type"], i["id"]))

    # ---- id/path resolution (studio insight endpoints) -------------------- #
    _TYPE_ALIASES = {"recipe": "recipes", "recipes": "recipes",
                     "skill": "skills", "skills": "skills", "native": "native"}

    def norm_type(self, item_type: str) -> Optional[str]:
        """Normalize singular/plural item-type spellings to the canonical plural."""
        return self._TYPE_ALIASES.get((item_type or "").lower())

    def resolve_filename(self, item_type: str, item_id: str) -> Optional[str]:
        """Map an item id (recipes/skills) or filename (native) to its filename."""
        t = self.norm_type(item_type)
        if t == "recipes":
            p = self._recipe_filepaths.get(item_id)
            if p:
                return os.path.basename(p)
            return item_id if (item_id or "").endswith(".md") and self._resolve_path("recipes", item_id) else None
        if t == "skills":
            p = self._skill_filepaths.get(item_id)
            if p:
                return os.path.basename(p)
            return item_id if (item_id or "").endswith(".md") and self._resolve_path("skills", item_id) else None
        if t == "native":
            return item_id if item_id in self.list_native_files() else None
        return None

    def native_provenance(self, filename: str) -> str:
        shp, ov = self._dirs("native")
        in_ov = os.path.exists(os.path.join(ov, filename))
        in_shp = os.path.exists(os.path.join(shp, filename))
        return "overridden" if (in_ov and in_shp) else ("overlay" if in_ov else "shipped")

    def get_item_detail(self, item_type: str, item_id: str) -> Dict[str, Any]:
        """Raw content + parsed frontmatter + provenance for one item (studio read view)."""
        t = self.norm_type(item_type)
        filename = self.resolve_filename(item_type, item_id)
        if not t or not filename:
            raise ValueError(f"Unknown {item_type} '{item_id}'.")
        if t == "recipes":
            raw = self.get_raw_recipe(filename)
            parsed = self.recipes[item_id].model_dump() if item_id in self.recipes else None
            prov = self.provenance("recipes", item_id)
        elif t == "skills":
            raw = self.get_raw_skill(filename)
            parsed = self.skills[item_id].model_dump() if item_id in self.skills else None
            prov = self.provenance("skills", item_id)
        else:  # native
            raw = self.get_raw_native(filename)
            parsed = None
            prov = self.native_provenance(filename)
        # All three types are editable-to-overlay now. Native carries a runtime caveat:
        # the executor does not yet load overlay native modules (write-only increment).
        return {"type": t, "id": item_id, "filename": filename, "provenance": prov,
                "editable": True, "runtime_pending": t == "native", "raw": raw, "parsed": parsed}

    def shipped_path(self, item_type: str, filename: str) -> str:
        """Absolute-ish path to the SHIPPED (git-tracked) copy of a file, used for git
        history/diff — the overlay is git-ignored so history only exists for shipped."""
        t = self.norm_type(item_type) or item_type
        return os.path.join(self._shipped[t], filename)

    def get_recipe(self, recipe_id: str) -> Optional[Recipe]:
        return self.recipes.get(recipe_id)

    def get_recipe_filepath(self, recipe_id: str) -> Optional[str]:
        return self._recipe_filepaths.get(recipe_id)

    def list_recipes(self) -> List[str]:
        return list(self.recipes.keys())

    def list_recipe_files(self) -> List[str]:
        """Sorted union of shipped + overlay recipe filenames."""
        return self._list_files("recipes")

    def get_raw_recipe(self, filename: str) -> str:
        """Raw content of a recipe file (overlay shadows shipped)."""
        path = self._resolve_path("recipes", filename)
        if not path:
            raise ValueError("Recipe file not found")
        with open(path, "r") as f:
            return f.read()

    def save_raw_recipe(self, filename: str, content: str):
        """Deep-validate and save a recipe to the OVERLAY (never mutates shipped IP)."""
        if not filename.endswith(".md"):
            filename += ".md"
        self._deep_validate("recipe", content, filename)
        self._write_overlay("recipes", filename, content)
        self.load_recipes()

    def list_skill_files(self) -> List[str]:
        """Sorted union of shipped + overlay skill filenames."""
        return self._list_files("skills")

    def get_raw_skill(self, filename: str) -> str:
        """Raw content of a skill file (overlay shadows shipped)."""
        path = self._resolve_path("skills", filename)
        if not path:
            raise ValueError("Skill file not found")
        with open(path, "r") as f:
            return f.read()

    def save_raw_skill(self, filename: str, content: str):
        """Deep-validate and save a skill to the OVERLAY (never mutates shipped IP)."""
        if not filename.endswith(".md"):
            filename += ".md"
        self._deep_validate("skill", content, filename)
        self._write_overlay("skills", filename, content)
        self.load_skills()

    # ---- native nodes (read; overlay-write lands in a later increment) ----- #
    def list_native_files(self) -> List[str]:
        """Sorted union of shipped + overlay native module filenames (.py, excl. dunder)."""
        return [f for f in self._list_files("native", ".py") if not f.startswith("__")]

    def get_raw_native(self, filename: str) -> str:
        path = self._resolve_path("native", filename)
        if not path:
            raise ValueError("Native module not found")
        with open(path, "r") as f:
            return f.read()

    def save_raw_native(self, filename: str, content: str):
        """Deep-validate (AST parse + sandbox-hazard scan) and save a native module to the
        OVERLAY. NOTE: overlay native modules are NOT yet loaded by the executor — that
        dynamic-load contract lands in a later increment; until then a running workflow
        uses the SHIPPED module. The Studio surfaces this caveat to the editor."""
        if not filename.endswith(".py"):
            filename += ".py"
        self._deep_validate("native", content, filename)
        self._write_overlay("native", filename, content)

    def _deep_validate(self, item_type: str, content: str, filename: str):
        """Run the shared deep validator (approach_docs/017 §3); raise on errors so every
        write path — studio, legacy editor, CI — is protected uniformly."""
        from gads.core.knowledge_validation import validate
        result = validate(item_type, content, registry=self, filename=filename)
        if result["errors"]:
            raise ValueError("; ".join(result["errors"]))

    @staticmethod
    def _trigger_hits(triggers: List[str], desc_lower: str) -> int:
        """Count triggers that match on a word boundary (not bare substring).

        Substring matching caused spurious loads — e.g. the trigger 'list' firing on
        'tolist()' or 'top' on a 'fi_top' variable. Word-boundary matching keeps
        multi-word phrase triggers ('auto ml', 'treatment effect') working while
        eliminating mid-token false positives that dilute a small model's attention.
        """
        hits = 0
        for t in triggers:
            pattern = r"\b" + re.escape(t.lower().strip()) + r"\b"
            if re.search(pattern, desc_lower):
                hits += 1
        return hits

    def find_skills(self, task_description: str) -> List[Skill]:
        """Returns skills that match triggers in the task description (case-insensitive)."""
        desc_lower = task_description.lower()
        return [
            skill for skill in self.skills.values()
            if self._trigger_hits(skill.triggers, desc_lower) > 0
        ]

    def find_skills_scored(self, task_description: str) -> List[tuple]:
        """Returns [(Skill, hit_count)] for skills with at least one trigger match."""
        desc_lower = task_description.lower()
        results = []
        for skill in self.skills.values():
            hits = self._trigger_hits(skill.triggers, desc_lower)
            if hits > 0:
                results.append((skill, hits))
        return results

    def find_skills_semantic(self, task_description: str) -> List[tuple]:
        """Returns [(Skill, cosine_similarity)] via the embedding index, best first.

        Empty when semantic matching is disabled/unavailable. Intended for tasks with
        NO curated attached_skills — callers keep compiled benchmark prompts stable by
        not augmenting curated tasks (see skill_semantics module docstring).
        """
        return [
            (self.skills[sid], score)
            for sid, score in self.semantic_index.find(task_description)
            if sid in self.skills
        ]

    def find_skills_combined(self, task_description: str) -> List[tuple]:
        """Union of keyword and semantic matches as [(Skill, source, score)].

        Keyword matches come first (exact signal beats similarity); a skill matched by
        both is reported once, as keyword.
        """
        keyword = self.find_skills_scored(task_description)
        seen = {s.id for s, _ in keyword}
        combined = [(s, "keyword", float(hits)) for s, hits in keyword]
        combined += [
            (s, "semantic", score)
            for s, score in self.find_skills_semantic(task_description)
            if s.id not in seen
        ]
        return combined

    def get_skills_summary(self) -> List[Dict[str, Any]]:
        """Returns available skills with IDs, descriptions (for agent selection) and
        triggers (for relevance pruning — strip triggers before serializing into prompts)."""
        return [{"id": s.id, "description": s.description, "triggers": s.triggers} for s in self.skills.values()]

    def get_recipes_summary(self) -> List[Dict[str, Any]]:
        """Returns a list of available recipes with their IDs and rationale for agent awareness."""
        return [{"id": r.id, "rationale": r.rationale, "applies_when": r.applies_when} for r in self.recipes.values()]

    def find_matches(self, intent_tags: Dict[str, Any], objective: str = "") -> List[Recipe]:
        """Every recipe whose `applies_when` covers these labels — the COVERAGE ORACLE.

        This answers a question the Router's LLM choice cannot: *given these labels, does a
        covering recipe exist at all?* That is what separates a genuine coverage gap (no
        recipe covers the task) from a selection error (one did, and the Router missed it) —
        see approach_docs/024. Deterministic, no LLM call.

        `objective` is optional and only used to evaluate `objective_contains` anti-signals.
        Recipes are returned ranked: signal hits first, then declaration order, so the head
        of the list is the best deterministic guess rather than an arbitrary dict order.

        NOTE the label vocabulary is not shared with `taxonomy.yaml` or with the Router's
        prompt enum (approach_docs/024 §1). Matching here is only as good as the caller's
        labels.
        """
        target_type = intent_tags.get("task_type")
        target_modality = intent_tags.get("data_modality")
        obj_low = (objective or "").lower()

        scored = []
        for recipe in self.recipes.values():
            applies = recipe.applies_when or {}
            if target_type not in (applies.get("task_type") or []):
                continue
            if target_modality not in (applies.get("data_modality") or []):
                continue
            # Anti-signals are what stop a broader recipe from swallowing a narrower one
            # (the AutoGluon recipes anti-signal model-comparison objectives precisely so
            # they do not grab them). Ignoring them here would over-report coverage.
            if self._anti_signals_fire(applies.get("anti_signals") or [], intent_tags, obj_low):
                continue
            scored.append((self._signal_score(applies.get("signals") or [], obj_low), recipe))

        scored.sort(key=lambda pair: -pair[0])
        return [r for _score, r in scored]

    @staticmethod
    def _anti_signals_fire(anti_signals, intent_tags: Dict[str, Any], obj_low: str) -> bool:
        """True when any anti-signal excludes this recipe for these labels/objective."""
        for anti in anti_signals:
            if not isinstance(anti, dict):
                continue
            for key, val in anti.items():
                if key == "objective_contains":
                    terms = val if isinstance(val, list) else [val]
                    if any(str(t).lower() in obj_low for t in terms):
                        return True
                elif intent_tags.get(key) == val:
                    return True
        return False

    @staticmethod
    def _signal_score(signals, obj_low: str) -> int:
        """How many positive `objective_contains` terms the objective hits."""
        score = 0
        for sig in signals:
            if not isinstance(sig, dict):
                continue
            terms = sig.get("objective_contains") or []
            terms = terms if isinstance(terms, list) else [terms]
            score += sum(1 for t in terms if str(t).lower() in obj_low)
        return score

    def classify_routing(self, chosen_id: Optional[str], candidates: List[Recipe]) -> str:
        """Verdict for one routing decision (approach_docs/024 §4).

        `drafted_gap` means "a gap GIVEN THESE LABELS" — a Router misclassification produces
        a phantom gap that looks identical here. Confirming a real gap needs a
        label-independent signal (semantic near-miss); that is phase 3, not this function.
        """
        cand_ids = {r.id for r in candidates}
        if chosen_id:
            return "routed_consistent" if chosen_id in cand_ids else "routed_off_manifest"
        return "drafted_miss" if cand_ids else "drafted_gap"
