import os
import re
import json
from typing import List, Dict, Any, Optional
import uuid
import base64
from jinja2 import Environment, FileSystemLoader

def create_master_reports(
    project_id: uuid.UUID,
    workspace_dir: str,
    narrative: str,
    takeaways: List[str],
    artifacts: List[Any],
    artifact_insights: Optional[List[Any]] = None
):
    """
    Assembles the final integrated HTML dashboard and Markdown research report.
    """
    insights_map = {}
    if artifact_insights:
        # artifact_insights can be list of dicts or pydantic models
        for ins in artifact_insights:
            if hasattr(ins, 'model_dump'):
                data = ins.model_dump()
            else:
                data = ins
            insights_map[data.get('artifact_id')] = data

    # 1. Generate Markdown Report
    takeaways_md = "\n".join([f"- {t}" for t in takeaways])
    md_content = f"""# Research Report: Project {project_id}

## Executive Summary
{narrative}

## Key Takeaways
{takeaways_md}

## Methodology & Findings
The following artifacts were generated during this analysis:
"""
    for a in artifacts:
        fname = a.content_json.get("filename")
        if a.type in ("interactive_plot", "json_plot"):
            md_content += f"- **{a.description}**: [View Plot]({fname})\n"
        elif a.type == "plot":
            md_content += f"- **{a.description}** (Static Image)\n"
        elif a.type == "handover_bundle":
            md_content += f"- **{a.description}**: [Download Offline Script]({fname})\n"

    with open(os.path.join(workspace_dir, "research_report.md"), "w") as f:
        f.write(md_content)

    # 2. Generate Integrated HTML Dashboard using Jinja2
    template_dir = os.path.join(os.path.dirname(__file__), "..", "templates")
    env = Environment(loader=FileSystemLoader(template_dir))
    template = env.get_template("dashboard.html.j2")

    cards = []
    for a in artifacts:
        card = {
            "description": a.description,
            "type": a.type,
            "caption": "Generated by GADS workflow.",
            "ctx_text": "",
            "json_data": None,
            "html_content": None,
            "img_b64": None,
            "filename": None
        }

        artifact_id_for_matching = ""
        
        if a.type == "json_plot":
            fname = a.content_json.get("filename")
            artifact_id_for_matching = fname
            fpath = os.path.join(workspace_dir, fname)
            if os.path.exists(fpath):
                with open(fpath, "r") as pf:
                    card["json_data"] = pf.read()
        
        elif a.type == "interactive_plot":
            # Legacy HTML
            card["type"] = "legacy_html"
            fname = a.content_json.get("filename")
            artifact_id_for_matching = fname
            fpath = os.path.join(workspace_dir, fname)
            if os.path.exists(fpath):
                with open(fpath, "r") as pf:
                    content = pf.read()
                    if "<body" in content:
                        card["html_content"] = content.split("<body")[1].split(">", 1)[1].split("</body>")[0]
                    else:
                        card["html_content"] = content
        
        elif a.type == "plot":
            # Static image base64
            img_b64 = a.content_json.get("image_base64")
            if img_b64:
                card["img_b64"] = img_b64
                artifact_id_for_matching = a.description # Use description for static plots
                card["type"] = "static_plot"
        
        elif a.type == "handover_bundle":
            fname = a.content_json.get("filename")
            card["filename"] = fname
            artifact_id_for_matching = fname

        # Skip rendering if we couldn't load the content
        if not (card["json_data"] or card["html_content"] or card["img_b64"] or card["filename"]):
            continue

        # Find matching insight
        artifact_id_for_matching = artifact_id_for_matching.lower()
        normalized_a_id = re.sub(r'[^a-z0-9]', '', artifact_id_for_matching)
        normalized_desc = re.sub(r'[^a-z0-9]', '', a.description.lower())
        
        insight = insights_map.get(artifact_id_for_matching)
        if not insight:
            # Fallback: fuzzy match on normalized IDs
            for key in insights_map.keys():
                normalized_key = re.sub(r'[^a-z0-9]', '', key.lower())
                if normalized_key in normalized_a_id or normalized_key in normalized_desc:
                    insight = insights_map[key]
                    break
        
        if insight:
            card["ctx_text"] = insight.get('contextual_text', "")
            card["caption"] = insight.get('caption', "Generated by GADS workflow.")

        # FINAL SAFETY CHECK: If it's a JSON plot but doesn't look like Plotly data, skip it
        if a.type == "json_plot" and card["json_data"]:
            try:
                js_test = json.loads(card["json_data"])
                if "data" not in js_test or not isinstance(js_test["data"], list):
                    print(f"  [Reporting] Skipping non-plotly JSON artifact: {a.description}")
                    continue
            except: continue

        cards.append(card)

    html_content = template.render(
        project_id=str(project_id),
        narrative=narrative,
        takeaways=takeaways,
        cards=cards
    )
    
    with open(os.path.join(workspace_dir, "final_dashboard.html"), "w") as f:
        f.write(html_content)

    return html_content
