import os
from typing import List, Dict, Any, Optional
import uuid
import base64

def create_master_reports(
    project_id: uuid.UUID,
    workspace_dir: str,
    narrative: str,
    takeaways: List[str],
    artifacts: List[Any],
    artifact_insights: Optional[List[Any]] = None
):
    """
    Assembles the final integrated HTML dashboard and Markdown research report.
    """
    insights_map = {}
    if artifact_insights:
        # artifact_insights can be list of dicts or pydantic models
        for ins in artifact_insights:
            if hasattr(ins, 'model_dump'):
                data = ins.model_dump()
            else:
                data = ins
            insights_map[data.get('artifact_id')] = data

    # 1. Generate Markdown Report
    takeaways_md = "\n".join([f"- {t}" for t in takeaways])
    md_content = f"""# Research Report: Project {project_id}

## Executive Summary
{narrative}

## Key Takeaways
{takeaways_md}

## Methodology & Findings
The following artifacts were generated during this analysis:
"""
    for a in artifacts:
        if a.type == "interactive_plot":
            fname = a.content_json.get("filename")
            md_content += f"- **{a.description}**: [View Interactive Plot]({fname})\n"
        elif a.type == "plot":
            md_content += f"- **{a.description}** (Static Image)\n"
        elif a.type == "handover_bundle":
             fname = a.content_json.get("filename")
             md_content += f"- **{a.description}**: [Download Offline Script]({fname})\n"

    with open(os.path.join(workspace_dir, "research_report.md"), "w") as f:
        f.write(md_content)

    # 2. Generate Integrated HTML Dashboard
    cards_html = ""
    for a in artifacts:
        inner_content = ""
        artifact_id_for_matching = ""
        
        if a.type == "interactive_plot":
            fname = a.content_json.get("filename")
            artifact_id_for_matching = fname
            fpath = os.path.join(workspace_dir, fname)
            if os.path.exists(fpath):
                with open(fpath, "r") as pf:
                    content = pf.read()
                    if "<body" in content:
                        inner_content = content.split("<body")[1].split(">", 1)[1].split("</body>")[0]
                    else:
                        inner_content = content
        
        elif a.type == "plot":
            # Static image base64
            img_b64 = a.content_json.get("image_base64")
            if img_b64:
                inner_content = f"<img src='data:image/png;base64,{img_b64}' style='max-width: 100%; border-radius: 8px;' />"
                artifact_id_for_matching = a.description # Use description for static plots
        
        elif a.type == "handover_bundle":
            fname = a.content_json.get("filename")
            inner_content = f"""
            <div style='padding: 20px; background: #fffbeb; border: 1px solid #fef3c7; border-radius: 8px; text-align: center;'>
                <p style='color: #92400e; font-weight: bold;'>⚠️ Heavy Computation Handover</p>
                <p>This task was bypassed due to high estimated runtime. Download the bundle to run the code locally.</p>
                <a href='{fname}' class='download-btn' style='display: inline-block; padding: 10px 20px; background: #d97706; color: white; text-decoration: none; border-radius: 6px; margin-top: 10px;'>Download Project Bundle (.zip)</a>
            </div>
            """
            artifact_id_for_matching = fname

        if inner_content:
            # Find matching insight
            insight = insights_map.get(artifact_id_for_matching)
            if not insight:
                # Fallback: fuzzy match on description (check if Figure N or filename is mentioned)
                for key in insights_map.keys():
                    if key.lower() in a.description.lower() or (artifact_id_for_matching and key.lower() in artifact_id_for_matching.lower()):
                        insight = insights_map[key]
                        break
            
            ctx_text = insight.get('contextual_text', "") if insight else ""
            caption = insight.get('caption', f"Generated by GADS workflow.") if insight else "Generated by GADS workflow."

            ctx_html = f"<div class='insight-text'>{ctx_text}</div>" if ctx_text else ""

            cards_html += f"""
            <div class='card'>
                <h2>{a.description}</h2>
                {ctx_html}
                <div class='plot-container'>{inner_content}</div>
                <div class='card-footer'>
                    <strong>{caption}</strong>
                </div>
            </div>
            """

    takeaways_html = "".join([f"<li>{t}</li>" for t in takeaways])

    html_content = f"""
    <html>
    <head>
        <title>GADS Research Synthesis</title>
        <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
        <style>
            body {{ font-family: 'Segoe UI', system-ui, sans-serif; margin: 40px auto; max-width: 1000px; background: #f8fafc; color: #1e293b; line-height: 1.6; }}
            .report-header {{ background: #ffffff; color: #0f172a; padding: 40px; border-radius: 12px; border: 1px solid #e2e8f0; margin-bottom: 20px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1); }}
            .report-header h1 {{ margin-top: 0; border-bottom: 3px solid #3b82f6; display: inline-block; padding-bottom: 5px; }}
            .report-body {{ background: #ffffff; padding: 40px; border-radius: 12px; box-shadow: 0 4px 20px rgba(0,0,0,0.05); border: 1px solid #e2e8f0; }}
            .card {{ border: 1px solid #cbd5e1; border-radius: 12px; padding: 25px; margin: 30px 0; background: #ffffff; }}
            .plot-container {{ min-height: 200px; text-align: center; }}
            .insight-text {{ font-size: 1.05rem; color: #475569; margin-bottom: 20px; padding: 15px; background: #f8fafc; border-radius: 8px; border-left: 4px solid #94a3b8; }}
            .card-footer {{ margin-top: 15px; font-size: 0.95rem; color: #1e293b; border-top: 1px solid #f1f5f9; padding-top: 10px; }}
            h1, h2, h3 {{ color: #0f172a; }}
            .takeaways {{ background: #eff6ff; border-left: 4px solid #3b82f6; padding: 25px; margin: 30px 0; border-radius: 0 8px 8px 0; }}
            .narrative {{ font-size: 1.15rem; color: #334155; margin-bottom: 40px; white-space: pre-wrap; background: #fff; }}
        </style>
    </head>
    <body>
        <div class='report-header'>
            <h1>Research Synthesis Report</h1>
            <p style='color: #64748b;'>Project ID: {project_id}</p>
        </div>
        <div class='report-body'>
            <h2>Executive Summary</h2>
            <div class='narrative'>{narrative}</div>
            
            <div class='takeaways'>
                <h3>Key Takeaways</h3>
                <ul>{takeaways_html}</ul>
            </div>

            <hr style='margin: 50px 0; border: 0; border-top: 2px solid #f1f5f9;' />
            
            <h2>Supporting Data Visualizations</h2>
            <p style='color: #64748b; margin-bottom: 40px;'>The following artifacts provide quantitative grounding for the summary above.</p>
            {cards_html}
        </div>
        <div style='text-align: center; margin-top: 40px; color: #94a3b8; font-size: 0.8rem;'>
            Generated by GADS (Generative-augmented Data Science)
        </div>
    </body>
    </html>
    """
    
    with open(os.path.join(workspace_dir, "final_dashboard.html"), "w") as f:
        f.write(html_content)

    return html_content
