import os
from typing import List, Dict, Any
import uuid

def create_master_reports(
    project_id: uuid.UUID,
    workspace_dir: str,
    narrative: str,
    takeaways: List[str],
    artifacts: List[Any]
):
    """
    Assembles the final integrated HTML dashboard and Markdown research report.
    """
    
    # 1. Generate Markdown Report
    takeaways_md = "\n".join([f"- {t}" for t in takeaways])
    md_content = f"""# Research Report: Project {project_id}

## Executive Summary
{narrative}

## Key Takeaways
{takeaways_md}

## Methodology & Findings
The following artifacts were generated during this analysis:
"""
    for a in artifacts:
        if a.type == "interactive_plot":
            fname = a.content_json.get("filename")
            md_content += f"- **{a.description}**: [View Interactive Plot]({fname})\n"
        elif a.type == "plot":
            md_content += f"- **{a.description}** (Static Image)\n"

    with open(os.path.join(workspace_dir, "research_report.md"), "w") as f:
        f.write(md_content)

    # 2. Generate Integrated HTML Dashboard
    # Filter for interactive plots and capture their descriptions
    cards_html = ""
    for a in artifacts:
        if a.type == "interactive_plot":
            fname = a.content_json.get("filename")
            fpath = os.path.join(workspace_dir, fname)
            if os.path.exists(fpath):
                with open(fpath, "r") as pf:
                    content = pf.read()
                    # Extract just the div part if it's a full plotly html
                    div = content.split("<body>")[1].split("</body>")[0] if "<body>" in content else content
                    
                    cards_html += f"""
                    <div class='card'>
                        <h2>{a.description}</h2>
                        <div class='plot-container'>{div}</div>
                        <div class='card-footer'>
                            <strong>Context:</strong> Verified by CodeGenerator as part of the analysis workflow.
                        </div>
                    </div>
                    """

    takeaways_html = "".join([f"<li>{t}</li>" for t in takeaways])

    html_content = f"""
    <html>
    <head>
        <title>GADS Research Synthesis</title>
        <style>
            body {{{{ font-family: 'Segoe UI', system-ui, sans-serif; margin: 40px auto; max-width: 1000px; background: #f8fafc; color: #1e293b; line-height: 1.6; }}}}
            .report-header {{{{ background: #ffffff; color: #0f172a; padding: 40px; border-radius: 12px; border: 1px solid #e2e8f0; margin-bottom: 20px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1); }}}}
            .report-header h1 {{{{ margin-top: 0; border-bottom: 3px solid #3b82f6; display: inline-block; padding-bottom: 5px; }}}}
            .report-body {{{{ background: #ffffff; padding: 40px; border-radius: 12px; box-shadow: 0 4px 20px rgba(0,0,0,0.05); border: 1px solid #e2e8f0; }}}}
            .card {{{{ border: 1px solid #cbd5e1; border-radius: 12px; padding: 25px; margin: 30px 0; background: #ffffff; }}}}
            .plot-container {{{{ min-height: 400px; }}}}
            .card-footer {{{{ margin-top: 15px; font-size: 0.9rem; color: #64748b; font-style: italic; border-top: 1px solid #f1f5f9; padding-top: 10px; }}}}
            h1, h2, h3 {{{{ color: #0f172a; }}}}
            .takeaways {{{{ background: #eff6ff; border-left: 4px solid #3b82f6; padding: 25px; margin: 30px 0; border-radius: 0 8px 8px 0; }}}}
            .narrative {{{{ font-size: 1.15rem; color: #334155; margin-bottom: 40px; white-space: pre-wrap; background: #fff; }}}}
        </style>
    </head>
    <body>
        <div class='report-header'>
            <h1>Research Synthesis Report</h1>
            <p style='color: #64748b;'>Project ID: {project_id}</p>
        </div>
        <div class='report-body'>
            <h2>Executive Summary</h2>
            <div class='narrative'>{narrative}</div>
            
            <div class='takeaways'>
                <h3>Key Takeaways</h3>
                <ul>{takeaways_html}</ul>
            </div>

            <hr style='margin: 50px 0; border: 0; border-top: 2px solid #f1f5f9;' />
            
            <h2>Supporting Data Visualizations</h2>
            <p style='color: #64748b; margin-bottom: 40px;'>The following interactive charts provide quantitative grounding for the summary above.</p>
            {cards_html}
        </div>
        <div style='text-align: center; margin-top: 40px; color: #94a3b8; font-size: 0.8rem;'>
            Generated by GADS (Generative-augmented Data Science)
        </div>
    </body>
    </html>
    \"\"\"
    
    with open(os.path.join(workspace_dir, "final_dashboard.html"), "w") as f:
        f.write(html_content)
